<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SubmissionTree" nsURI="http://submissiontree.ecore" nsPrefix="SubmissionTree">
  <eClassifiers xsi:type="ecore:EClass" name="Assignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Assignment"
        eOpposite="#//Assignment/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Assignment" containment="true" eOpposite="#//Assignment/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submissions" upperBound="-1"
        eType="#//Submisison" containment="true" eOpposite="#//Submisison/assignment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Submisison">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="answer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manualGrade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="student" lowerBound="1"
        eType="#//Student" eOpposite="#//Student/submissions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignment" lowerBound="1"
        eType="#//Assignment" eOpposite="#//Assignment/submissions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Student">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="submissions" upperBound="-1"
        eType="#//Submisison" eOpposite="#//Submisison/student"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MyContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="students" upperBound="-1"
        eType="#//Student" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" upperBound="-1"
        eType="#//Assignment" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
